--Dátumokat ellenõrizni
DECLARE
   L_SESSION_ID NUMBER;
BEGIN
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_FDB_DMEXBA_STA_EXBAGC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000',P_ASYNC_FL => TRUE);

   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_SYM_RBACCT_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_SYM_RBACCT_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_CMS_CMCACV_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_CMS_CMCACV_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_CMS_CMCACC_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_CMS_CMCACC_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);

   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_CMS_CMCINS_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_CMS_CMCINS_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_FAC_AGREEM_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_FAC_INVOIC_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_LZA_ARRANG_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_LZA_ARRANG_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_LZI_ARRANG_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_LZI_ARRANG_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_SYM_CLDRAW_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_SYM_CLDRAW_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_SYM_CLGUAR_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_SYM_CLGUAR_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_SYM_CLLOAN_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_SYM_CLLOAN_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_SYM_RBODFA_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_SYM_RBODFA_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_TBR_DEALBA_DW_PRODUC', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);
   L_SESSION_ID := LP_EXECUTER.RUN_STANDALONE_SCENARIO(P_SCEN_NAME => 'MAP_TBR_DEALBA_DW_ARRANG', P_SCEN_VERSION => '001', P_INSTANCE_NAME => 'EDWPROT1', P_SCEN_PARAMETERS => 'GLOBAL.P_EFFECTIVE_LOAD_DATE=20170630000000', P_ASYNC_FL => TRUE);

   DBMS_OUTPUT.PUT_LINE(L_SESSION_ID);
END;
/

--Törlés
ALTER SESSION ENABLE PARALLEL DML;

DELETE 
        EBH_DW.PRODUCT
WHERE  END_OF_VALIDITY = DATE '2017-06-30';

commit;

DELETE 
        EBH_DW.ARRANGEMENT
WHERE  END_OF_VALIDITY = DATE '2017-06-30';
 
commit;